### ISSUE TITLE
Blank pages after contents

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#86] opened 2014-12-27 14:49 UTC
I noticed 2 blank pages after the contents. I'm not certain if this is intended. Also, the second blank page has the following header:

![header](https://i.imgur.com/2OUPl9M.png)

Could someone point out if this is intentional?

**Comment by pharpend** [comment] 2014-12-27 14:55
@wei2912 it's an artifact of LaTeX's `book` document class, not a bug. I'm sure can change it if you want, but I don't think it's a big deal. Closing as not a bug.

**Closed as completed by pharpend** 2014-12-27 14:55 UTC
Labels: question

**Comment by ghost** [comment] 2014-12-27 17:15
Isn't that page # in the wrong place?

**Comment by pharpend** [comment] 2014-12-27 17:46
@beingbrown it varies based on whether the page is even or odd, the idea being that there would be room for the spine if the book were to be printed into an actual book.
