### ISSUE TITLE
Branches for each chapter

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#54] opened 2014-12-24 17:40 UTC
I suggest that we have branches for each chapter, so that we can collaborate together on each chapter. The current system requires us to make a PR from our own fork. This works fine for small changes, but not for large edits such as writing chapters.

I've created the branch [chap2](https://github.com/learnmath/lysa/tree/chap2), so edits can go there in the future.

**Comment by pharpend** [comment] 2014-12-24 17:46
This is in direct violation of the [branching schema](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by pharpend** [comment] 2014-12-24 17:48
[The branching schema](http://nvie.com/posts/a-successful-git-branching-model/)

> Feature branches (or sometimes called topic branches) are used to develop new features for the upcoming or a distant future release. When starting development of a feature, the target release in which this feature will be incorporated may well be unknown at that point. The essence of a feature branch is that it exists as long as the feature is in development, but will eventually be merged back into develop (to definitely add the new feature to the upcoming release) or discarded (in case of a disappointing experiment).
> 
> Feature branches typically exist in developer repos only, not in origin.

@beingbrown , opinion?

**Comment by wei2912** [comment] 2014-12-24 17:49
I personally feel that an exception should be made for this, but I'll wait for others' opinion.

**Comment by pharpend** [comment] 2014-12-24 17:52
I had this argument with @beingbrown last night, and I came to agree with him that this is not a case where an exception should be made.

I do think our current development model (i.e. no feature branches in lm) will become problematic once the book becomes more mature. However, for the time being, there's really nothing wrong with having everything in develop.

**Comment by wei2912** [comment] 2014-12-24 18:35
True.

**Comment by ghost** [comment] 2014-12-24 21:01
The proposed solution is to add upstreams to collaborators if you're working on a chapter together. We can add this to the contrib guide if necessary. Closing working as intended.

**Closed as completed by ghost** 2014-12-24 21:01 UTC
Labels: invalid
